Repository theohbrothers/docker-imap-backup, pull requests merged in 2023-09, with the labels that each got.

#25 Refactor: Move versions from `VARIANTS.ps1` to `versions.json`
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
Labels: refactor

#28 Fix: Remove need for `ConvertFrom-Json -Depth` in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: fix

#29 Enhancement: Scope changed versions to 'patch' in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: enhancement

#30 Fix: Preserve array when using `ConvertFrom-Json` in `VARIANTS.ps1`
  generate/definitions/VARIANTS.ps1
Labels: fix

#31 Fix (ci): Regenerate missing `cron` job
  .github/workflows/cron.yml
Labels: fix

#27 Enhancement (ci): Add `on: merge_group` for merge queue support
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: enhancement

#33 Enhancement: Add v11.1.0 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/11.1.0/Dockerfile
  variants/11.1.0/docker-entrypoint.sh
Labels: enhancement

#35 Enhancement: Add v9.3.2 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/9.3.2/Dockerfile
  variants/9.3.2/docker-entrypoint.sh
Labels: enhancement

#36 Hotfix: Exclude `10.0.0` variants since it is a bad release
  Update-Versions.ps1
Labels: hotfix

#37 Enhancement: Add v12.0.0 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/12.0.0/Dockerfile
  variants/12.0.0/docker-entrypoint.sh
Labels: enhancement

#38 Docs (readme): Update Variant versions section
  README.md
  generate/templates/README.md.ps1
Labels: docs

#39 Enhancement (ci): Remove ` $env:GITHUB_TOKEN` in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: enhancement

#40 Refactor (ci): Use new `versions.json` config
  Update-Versions.ps1
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
Labels: refactor

#41 Enhancement (ci): Add `workflow_dispatch` to `cron` job
  .github/workflows/cron.yml
  generate/definitions/versions.json
  generate/templates/.github/workflows/cron.yml.ps1
Labels: enhancement

#42 Enhancement: Add imap-backup 12.1.0 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/12.1.0/Dockerfile
  variants/12.1.0/docker-entrypoint.sh
Labels: enhancement

#43 Enhancement (ci): Add support for incremental variants
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: enhancement

#44 Refactor (ci): Use a `job_group_key` to group jobs
  .github/workflows/ci-master-pr.yml
  .vscode/tasks.json
  generate/definitions/VARIANTS.ps1
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: refactor
